version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-load-balancer-lab09
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web-net
    depends_on:
      - web-server-1
      - web-server-2
      - web-server-3
      - web-server-4

  web-server-1:
    image: nginx:alpine
    container_name: web1
    ports:
      - "8081:80"
    networks:
      - web-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    entrypoint: 
      - /bin/sh
      - -c
      - |
        echo "<h1>Web 1: rachata-pimsupsiri-1660705805-328A | Host: $$(hostname) | IP: $$(hostname -i)</h1>" > /usr/share/nginx/html/index.html
        nginx -g 'daemon off;'

  web-server-2:
    image: nginx:alpine
    container_name: web2
    ports:
      - "8082:80"
    networks:
      - web-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    entrypoint: 
      - /bin/sh
      - -c
      - |
        echo "<h1>Web 2: rachata-pimsupsiri-1660705805-328A | Host: $$(hostname) | IP: $$(hostname -i)</h1>" > /usr/share/nginx/html/index.html
        nginx -g 'daemon off;'

  web-server-3:
    image: nginx:alpine
    container_name: web3
    ports:
      - "8083:80"
    networks:
      - web-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    entrypoint: 
      - /bin/sh
      - -c
      - |
        echo "<h1>Web 3: rachata-pimsupsiri-1660705805-328A | Host: $$(hostname) | IP: $$(hostname -i)</h1>" > /usr/share/nginx/html/index.html
        nginx -g 'daemon off;'

  web-server-4:
    image: nginx:alpine
    container_name: web4
    ports:
      - "8084:80"
    networks:
      - web-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    entrypoint: 
      - /bin/sh
      - -c
      - |
        echo "<h1>Web 4: rachata-pimsupsiri-1660705805-328A | Host: $$(hostname) | IP: $$(hostname -i)</h1>" > /usr/share/nginx/html/index.html
        nginx -g 'daemon off;'

networks:
  web-net:
    driver: bridge